FROM python:3.9.4-alpine3.13

RUN apk --update add --no-cache g++ bash

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8888

WORKDIR /var/workdir/

COPY start.sh .

CMD ["bash", "start.sh"]
