name: pyds

channels:
  - conda-forge
  - anaconda

dependencies:
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - pandas=1.2.4
  - seaborn=0.11.1
  - ipykernel=5.5.5
  - ipython=7.23.1
  - notebook=6.4.0
  - jupyterlab=3.0.16
  - pip:
    - tqdm==4.60.0
